### ISSUE TITLE
problem of matrix non symmetric positive definite

### ISSUE THREAD

**Issue by carneaup** [bridges-libraries/BRIDGES#8]
Can't Solve Cholesky since LHS matrix is apparently not symmetric positive definite.

**Comment by romainmesnil** [comment]
Hi Paul,
[Cholesky decomposition](https://en.wikipedia.org/wiki/Cholesky_decomposition) is supposed to be applied to SDP matrices only. If you are supposed to use Cholesky (or LDL) decomposition in an algorithm, please check the construction of the left-hand side matrix.
Could you provide us a minimal working example?
Best,
Romain

**Comment by nrmontagne** [comment]
Hi Paul,
Is your problem solved ? 
Regards
Nicolas

**Comment by carneaup** [comment]
Yes, it's all good.
